spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.95.28:3306/shawf-blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: li1329
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.shawf: info
server:
  port: 8081


